routes/web.php
<?php

Route::prefix('admin')->middleware('auth')->group(function() {
    // Route::prefix('movie')->group(function() {
    //     Route::get('', 'AdminController@indexMovie');
    //     Route::get('create', 'AdminController@createMovie');
    //     Route::post('store', 'AdminController@storeMovie');
    //     Route::get('edit/{id}', 'AdminController@editMovie');
    //     Route::put('edit/update/{id}', 'AdminController@updateMovie');
    //     Route::get('delete/{id}', 'AdminController@destroyMovie');

    //     Route::resource('movie', 'AdminMovieController');
    // });
    Route::resource('movie', 'AdminMovieController');
    
    Route::prefix('booking')->group(function() {
        Route::get('', 'AdminController@indexBooking');
        Route::get('edit/{id}', 'AdminController@editBooking');
        Route::put('edit/update/{id}', 'AdminController@updateBooking');
        Route::get('delete/{id}', 'AdminController@destroyBooking');
        Route::get('verif', 'AdminController@indexVerif');
        Route::post('verif/check', 'AdminController@checkToken');
        Route::get('verif/index/{id}','AdminController@indexCheck');
        Route::post('verif/return', 'AdminController@checkReturn');
        Route::get('verif/index/pay/{id}/{paid}', 'AdminController@indexPay');
        Route::post('verif/pay', 'AdminController@payTicket');
    });
    Route::prefix('user')->group(function() {
        Route::get('register', 'AdminController@createUser');
        Route::post('store', 'AdminController@storeUser');
        Route::get('', 'AdminController@indexUser');
        Route::get('edit/{id}', 'AdminController@editUser');
        Route::put('edit/update/{id}', 'AdminController@updateUser');
        Route::get('delete/{id}', 'AdminController@destroyUser');
    });
});

Route::prefix('user')->group(function() {
    Route::get('', 'UserController@index');
    Route::get('detail/{id}', 'UserController@createBooking');
    Route::post('book/store', 'UserController@storeBooking');
    Route::get('upcoming', 'UserController@indexUpcoming');
    Route::get('views', 'UserController@indexView');
    Route::get('rating', 'UserController@indexRating');
    Route::get('detail2/{id}', 'UserController@showDetailUpcoming');
});

Route::prefix('auth')->group(function() {
    Route::get('login', 'AuthController@loginShow')->name('login');
    Route::post('login/check', 'AuthController@loginAuth');
    Route::get('logout', 'AuthController@logoutAuth');
});

app/Movie.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Movie extends Model
{
    use SoftDeletes;

    protected $table = 'movie';
    protected $fillable = ['title', 'description', 'rate', 'seats', 'duration', 'starting_date', 'ending_date', 'time', 'image', 'price'];
}

resources/views/admin/movie/create.blade.php
@extends('admin.master')
@section('movie.create')
<!-- Main content -->
<!-- general form elements -->
    <div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Add New Movie</h3>
        <a href="/admin/movie" class="btn btn-primary" style="float: right;">Back</a>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form method="post" action="{{ route('movie.store') }}" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{ method_field('POST') }}
        <div class="box-body">
                
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Movie Title" name="title">
                @if($errors->has('title'))
                <div class="text-danger">
                    {{ $errors->first('title')}}
                </div>
                @endif
            </div>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Movie Description" name="description">
                @if($errors->has('description'))
                <div class="text-danger">
                    {{ $errors->first('description')}}
                </div>
                @endif
            </div>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Movie Rating" name="rate">
                @if($errors->has('rate'))
                <div class="text-danger">
                    {{ $errors->first('rate')}}
                </div>
                @endif
            </div>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Movie Price" name="price">
                @if($errors->has('price'))
                <div class="text-danger">
                    {{ $errors->first('price')}}
                </div>
                @endif
            </div>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Movie Seats" name="seats">
                @if($errors->has('seats'))
                <div class="text-danger">
                    {{ $errors->first('seats')}}
                </div>
                @endif
            </div>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Movie Duration" name="duration">
                @if($errors->has('duration'))
                <div class="text-danger">
                    {{ $errors->first('duration')}}
                </div>
                @endif
            </div>
            <div class="form-group">
                <input type="date" class="form-control" name="startingDate">
                @if($errors->has('startingDate'))
                <div class="text-danger">
                    {{ $errors->first('startingDate')}}
                </div>
                @endif
            </div>
            <div class="form-group">
                <input type="date" class="form-control" name="endingDate">
                @if($errors->has('endingDate'))
                <div class="text-danger">
                    {{ $errors->first('endingDate')}}
                </div>
                @endif
            </div>
            <div class="form-group">
                <input type="time" class="form-control" name="time">
                @if($errors->has('time'))
                <div class="text-danger">
                    {{ $errors->first('time')}}
                </div>
                @endif
            </div>
            <div class="form-group">
                <label for="exampleInputFile">Movie Poster</label>
                <input type="file" name="image">
                @if($errors->has('image'))
                <div class="text-danger">
                    {{ $errors->first('image')}}
                </div>
                @endif
            </div>

        </div>
        <!-- /.box-body -->

        <div class="box-footer">
        <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
@endsection

resources/views/admin/movie/edit.blade.php
@extends('admin.master')
@section('movie.edit')
<!-- Main content -->
<!-- general form elements -->
    <div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Edit Movie</h3>
        <a href="/admin/movie" class="btn btn-primary" style="float: right;">Back</a>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form method="post" action="{{ route('movie.update', $movies->id) }}" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{ method_field('PUT')}}
        <div class="box-body">
                
            <div class="form-group">
                <input type="text" class="form-control" name="title" value="{{ $movies->title }}">
                @if($errors->has('title'))
                <div class="text-danger">
                    {{ $errors->first('title')}}
                </div>
                @endif
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="description" value="{{ $movies->description }}">
                @if($errors->has('description'))
                <div class="text-danger">
                    {{ $errors->first('description')}}
                </div>
                @endif
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="rate" value="{{ $movies->rate }}">
                @if($errors->has('rate'))
                <div class="text-danger">
                    {{ $errors->first('rate')}}
                </div>
                @endif
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="price" value="{{ $movies->price }}">
                @if($errors->has('price'))
                <div class="text-danger">
                    {{ $errors->first('price')}}
                </div>
                @endif
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="seats" value="{{ $movies->seats }}">
                @if($errors->has('seats'))
                <div class="text-danger">
                    {{ $errors->first('seats')}}
                </div>
                @endif
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="duration" value="{{ $movies->duration }}">
                @if($errors->has('duration'))
                <div class="text-danger">
                    {{ $errors->first('duration')}}
                </div>
                @endif
            </div>
            <div class="form-group">
                <input type="date" class="form-control" name="startingDate" value="{{ $movies->starting_date }}">
                @if($errors->has('startingDate'))
                <div class="text-danger">
                    {{ $errors->first('startingDate')}}
                </div>
                @endif
            </div>
            <div class="form-group">
                <input type="date" class="form-control" name="endingDate" value="{{ $movies->ending_date }}">
                @if($errors->has('endingDate'))
                <div class="text-danger">
                    {{ $errors->first('endingDate')}}
                </div>
                @endif
            </div>
            <div class="form-group">
                <input type="time" class="form-control" name="time" value="{{ $movies->time }}">
                @if($errors->has('time'))
                <div class="text-danger">
                    {{ $errors->first('time')}}
                </div>
                @endif
            </div>
            <div class="form-group">
                <label for="exampleInputFile">Current Image is {{ $movies->image }}</label>
                <input type="file" name="image">
                @if($errors->has('image'))
                <div class="text-danger">
                    {{ $errors->first('image')}}
                </div>
                @endif
            </div>

        </div>
        <!-- /.box-body -->

        <div class="box-footer">
        <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
@endsection

resources/views/admin/movie/index.blade.php
@extends ('admin.master')
@section ('movie.index')
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Movies Data
      </h1>
      @if (Session::has('alert'))
      <div class="alert alert-success alert-dismissible" style="margin: 0px;">
          <a href="admin/movie"><button type="button" class="close" data-dismiss="alert">&times;</button></a>
          {{Session::get('alert')}}
      </div>
      @endif
      @if (Session::has('alert-danger'))
      <div class="alert alert-danger alert-dismissible" style="margin: 0px;">
          <a href="admin/movie"><button type="button" class="close" data-dismiss="alert">&times;</button></a>
          {{Session::get('alert-danger')}}
      </div>
      @endif
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-body">
              <table id="example1" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <style>th{text-align: center;}</style>
                  <th>Id</th>
                  <th>Title</th>
                  <th>Description</th>
                  <th>Rate</th>
                  <th>Price</th>                  
                  <th>Seats</th>
                  <th>Duration</th>
                  <th>Image</th>
                  <th>Starting Date</th>
                  <th>Ending Date</th>
                  <th>Time</th>
                  <th class="col-md-2">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($movies as $m)
                <tr>
                  <td>{{ $m->id }}</td>
                  <td>{{ $m->title }}</td>
                  <td>{{ $m->description }}</td>
                  <td>{{ $m->rate }}*</td>
                  <td>{{ number_format($m->price) }}</td>
                  <td>{{ $m->seats }}</td>
                  <td>{{ $m->duration }}</td>
                  <td><img src="{{ asset('/images/'. $m->image)}}" height="100px" width="100px" alt=""></td>
                  <td>{{ $m->starting_date }}</td>
                  <td>{{ $m->ending_date }}</td>
                  <td>{{ $m->time }}</td>
                  <td> <form action="{{ route('movie.destroy', $m->id) }}" method="post">{{ method_field('DELETE') }}{{ csrf_field() }}<a style="margin-left: 20px;" href="{{ route('movie.edit', $m->id) }}" class="btn btn-warning">Edit</a>
                       <button class="btn btn-danger" onClick="return confirm('Are you sure to delete this data?')">Delete</button></form>
                  </td>
                </tr>
                @endforeach
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection