routes/web.php
<?php

Route::prefix('admin')->middleware('auth')->group(function() {
    // Route::prefix('movie')->group(function() {
    //     Route::get('', 'AdminController@indexMovie');
    //     Route::get('create', 'AdminController@createMovie');
    //     Route::post('store', 'AdminController@storeMovie');
    //     Route::get('edit/{id}', 'AdminController@editMovie');
    //     Route::put('edit/update/{id}', 'AdminController@updateMovie');
    //     Route::get('delete/{id}', 'AdminController@destroyMovie');

    //     Route::resource('movie', 'AdminMovieController');
    // });
    Route::resource('movie', 'AdminMovieController');
    
    Route::prefix('booking')->group(function() {
        Route::get('', 'AdminController@indexBooking');
        Route::get('edit/{id}', 'AdminController@editBooking');
        Route::put('edit/update/{id}', 'AdminController@updateBooking');
        Route::get('delete/{id}', 'AdminController@destroyBooking');
        Route::get('verif', 'AdminController@indexVerif');
        Route::post('verif/check', 'AdminController@checkToken');
        Route::get('verif/index/{id}','AdminController@indexCheck');
        Route::post('verif/return', 'AdminController@checkReturn');
        Route::get('verif/index/pay/{id}/{paid}', 'AdminController@indexPay');
        Route::post('verif/pay', 'AdminController@payTicket');
    });
    Route::prefix('user')->group(function() {
        Route::get('register', 'AdminController@createUser');
        Route::post('store', 'AdminController@storeUser');
        Route::get('', 'AdminController@indexUser');
        Route::get('edit/{id}', 'AdminController@editUser');
        Route::put('edit/update/{id}', 'AdminController@updateUser');
        Route::get('delete/{id}', 'AdminController@destroyUser');
    });
});

Route::prefix('user')->group(function() {
    Route::get('', 'UserController@index');
    Route::get('detail/{id}', 'UserController@createBooking');
    Route::post('book/store', 'UserController@storeBooking');
    Route::get('upcoming', 'UserController@indexUpcoming');
    Route::get('views', 'UserController@indexView');
    Route::get('rating', 'UserController@indexRating');
    Route::get('detail2/{id}', 'UserController@showDetailUpcoming');
});

Route::prefix('auth')->group(function() {
    Route::get('login', 'AuthController@loginShow')->name('login');
    Route::post('login/check', 'AuthController@loginAuth');
    Route::get('logout', 'AuthController@logoutAuth');
});

resources/views/admin/layout/header.blade.php
<!-- Main Header -->
<header class="main-header" style="position: fixed; width: 100%;">

<!-- Logo -->
<a href="/admin/movie" class="logo">
  <span class="logo-lg"><b>Movie</b>Admin</span>
</a>

<!-- Header Navbar -->
<nav class="navbar navbar-static-top" role="navigation">
  <!-- Sidebar toggle button-->
  <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
    <span class="sr-only">Toggle navigation</span>
  </a>
  <a href="{{ url('auth/logout') }}" class="btn btn-danger" style="float: right; margin: 10px 10px;" onClick="return confirm('Apakah yakin untuk logout?')">Logout</a>
  </div>
</nav>
</header>

resources/views/admin/layout/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar" style="position: fixed;">

<!-- sidebar: style can be found in sidebar.less -->
<section class="sidebar" >

  <!-- Sidebar Menu -->
  <ul class="sidebar-menu" data-widget="tree">
    
    <li class="header">MENU</li>
    <!-- Optionally, you can add icons to the links -->
    <li class="treeview">
          <a href="#"><i class="fa fa-link"></i> <span>Movie</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="/admin/movie">Movie List</a></li>
            <li><a href="{{ route('movie.create') }}">Add New Movie</a></li>
          </ul>
    </li>
    <li class="treeview">
          <a href="#"><i class="fa fa-link"></i> <span>Booking</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ url('admin/booking/') }}">Booking List</a></li>
            <li><a href="{{ url('admin/booking/verif') }}">Verification</a></li>
          </ul>
    </li>
    <li class="treeview">
          <a href="#"><i class="fa fa-link"></i> <span>Admin Account</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ url('admin/user') }}">Account List</a></li>
            <li><a href="{{ url('admin/user/register') }}">Create Account</a></li>
          </ul>
    </li>

  </ul>
  <!-- /.sidebar-menu -->
</section>
<!-- /.sidebar -->
</aside>